name: Generate Sims

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      APIKEY: ${{ secrets.RAIDBOTSAPI }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: talent sims
        run: python generate_by_talent.py $APIKEY
      - name: commit changes
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          git pull --rebase --autostash
          git add .
          git commit -m "update sims"
          git push
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: generate_sims
          path: |
            by_*.html
            *.js
