name: Generate JSON

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - uses: actions/cache@v2
        with:
          key: cache-${{ github.sha }}
          path: ${{ env.pythonLocation }}

  run_sims:
    runs-on: ubuntu-latest
    needs: [ setup ]
    strategy:
      max-parallel: 1
      matrix:
        args: [ --targets=1, --targets=2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: cache-${{ github.sha }}
          path: ${{ env.pythonLocation }}
      - run: |
          rm *.json
          python generate_combo.py ${{ matrix.args }} ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./*.json
