name: Update JSON

on:
  workflow_dispatch:

jobs:
  run_sims:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 0
      matrix:
        args: [ --targets=1, --targets=2 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: |
          rm -f *.json
          python generate_combo.py ${{ matrix.args }} ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./*.json
