name: Update JSON

on:
  workflow_dispatch:

jobs:
  one_target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 1 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_1.json

  two_target:
    needs: [ one_target ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 2 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_2.json

  three_target:
    needs: [ two_target ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 3 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_3.json

  four_target:
    needs: [ three_target ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 4 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_4.json

  five_target:
    needs: [ four_target ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 5 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_5.json

  dungeon:
    needs: [ five_target ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -d -m ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_d.json

  spread:
    needs: [ dungeon ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -s ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_s.json

  one_target_move:
    needs: [ spread ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 1 -m ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          name: json
          path: combo_1m.json

  commit:
    needs: [ spread ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: json
      - name: commit JSON
        run: |
          git config user.name Balance-SimC
          git config user.email Balance-SimC@github.com
          if [ -z "$(git status --porcelain)" ]; then
            echo "no updates to JSON"
          else
            git add .
            git commit -m "update JSON"
            git push
          fi
