name: Update JSON

on:
  workflow_dispatch:

jobs:
  run_sims:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: update python
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - run: python generate_combo.py -t 1 ${{ secrets.RAIDBOTSAPI }}
      - run: python generate_combo.py -t 2 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./*.json
