name: Update JSON

on:
  workflow_dispatch:

jobs:
  one_target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install requests
      - run: python generate_combo.py -t 1 ${{ secrets.RAIDBOTSAPI }}
      - uses: actions/upload-artifact@v2
        with:
          path: ./*.json
